### ISSUE TITLE
Port The Vedic Index of Names and Subjects to babylon format

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/stardict-sanskrit#10]
Source [here](http://www.sanskrit-lexicon.uni-koeln.de/scans/VEIScan/2014/web/index.php).
Example of babylon format [here](https://github.com/sanskrit-coders/stardict-sanskrit/blob/master/sa-head/apte-sa/apte-sa.babylon_final).

**Comment by damooo** [comment]
i started them already. and as i have no net in my village, i will push all things i done once a week, when i come to city : )  .  hope it will not be problem : )

**Comment by vvasuki** [comment]
Not a problem!

**Comment by vvasuki** [comment]
dAmodara - just to double check - you're working on this as well?

**Comment by damooo** [comment]
ha...

**Comment by damooo** [comment]
Updated bhai. 
Dictionary files for vedic index.

1. HEaders contains devanagari,optitransed,telugu,kannada headwords

2. Entire content is organised in html tags. So every part of content and display
   is hooked with classes, and ids . see list at bottom of this file.

3. As every thing is sectioned like title section, content section, foot notes section
   and all special instances like head words, bold text, italic texts, etc.. are hooked
   with class, we can alter appearance of any part with  change in CSS.
   and can thus change ui, or display quickly.

4. foot notes are seperated from content, and given at bottom of every word
   and a superlink is given to link to foot notes, and a backlink is there from
   footnote too.

5. when we click a footnote link , it takes us to footnote, along with that
   it will thematically heighlights that footnote from remaining. same when
   clicked backlink.

6. all possible words which are in present dict, are hyperlinked. So instead 
   of double clicks ,etc..  now can click on main hyperlinks. And it will help
   when we are updating it in any wiki too, so that main words are hyperlinked.

7. every word has page number, and word count in title bar. and each word
   given a uniq id, which may help in future.

8.  We can extract each word, and can make html page,if needed, as everything is 
    compatable.


-------------Used tags, classes------------------------------------

<div>	: screen , patra , contnt , footnts, headtitle,floatlr,pnum
<p>	:intl,mdl,ftpg
<a>	:pada,ftnt,ftbk,pglink
<span>	:bldtxt,headwd,itlctxt,ftbks,widetxt,unrdbl,wnum
<ol>	:olft,oftb,oftc

and id for foot notes are in form of " fx[0-9][0-9bc]*_ve1_WORDID ".
that final word no. is appended as goldendict ids will clash.
And back referances ids are in format of "#ref[0-9][0-9bc]*_ve1_WORDID ".

**Comment by damooo** [comment]
Some sample words:
kurukshetra
takshan
aksha
upanishad

etc... these i tested.

**Comment by vvasuki** [comment]
nice work, dAmodara!

* Can you use _vei1_pn1 instead of vei1_pn1? I am afraid that it will mess with autocomplete in dictionary apps. Eg - typing ve will show up all these page number entries - which will trouble the user.

* There are some spurious numeral keywords - ३। अक्ष|अक्ष|akṣa|akSha|అక్ష|ಅಕ್ಷ|_vei1@6|vei1_pn5. ३ in this entry needs to be removed.

* The entries have html like - 
`<style>  body{ margin: 20px; padding:0em; }  div.screen{ font-family:Verdana, "Lucida Sans Unicode", sans-serif; margin: 0em; line-height:1.5em; }  div.headtitle{ width:10em; height:3em; float:left; text-align:left; }  `  I doubt if that works in dictionary apps. Can you trim that please?

**Comment by vvasuki** [comment]
Also, can you add optitrans shortcut x for kSh? That is, kuruxetra, axa, taxan etc..

**Comment by damooo** [comment]
ok, will do that, and that css works in mobile apps too. checked it. 
before words started there are some #notes which will facilitate this.
like 
#stripmethod=keep
#sametypesequence=h
#bookname=VedaIndex
#author=shriram

**Comment by damooo** [comment]
those numerals i kept bcz, otherwise, it means loss of some data i thought, and added numeral removed word also, so that no problem occur. but seems still has problem in sorting of results. so other option is to send that word to last, instead of deleting it. which one?

**Comment by vvasuki** [comment]
aah - ३। अक्ष| has a । after ३, not |. Ok I understand now. It's fine as it is - but it is better to move the numeral to the end, and add a suffix "vedic_index" since it is relevant only to this dictionary.

So, ३। अक्ष ------> अक्ष (३ vedic_index).

**Comment by vvasuki** [comment]
dAmodara, also regarding folder and file names:
Please name the folder vedic_index. And the dictionary files should be named vedic_index.babylon etc.. They should not have a version number. (This is important for various installation scripts to work correctly.)

**Comment by damooo** [comment]
updated.
1. page no, head words appended with underscore, 'x' added for 'kSh' , in headers.
2. numeral appended heads pushed inside as second headers. so that priorities doesn't clash.
    search and check sorting order of results for  'go (गॊ) ' for example in previous, and present 
    version.
3. navigation links added in title bar. So for next word, previous word, next page, previous page
    there are arrow links. so can study continuesly.
4. wrong page links for second half corrected.
5. removed unnecessary white space coming in mobile apps, which is wasting screen space. now no 
   white margin in mobile apps.

**Comment by vvasuki** [comment]
Alas - for some reason, golden dict on ubuntu desktop does not display the html correctly anymore. @damooo - any ideas why?

**Comment by damooo** [comment]
I am using arch linux... ubuntu too should display well.. can you post a screen shot, and html source of result page in goldendict once, so that i can understand problem..

**Comment by vvasuki** [comment]
Looking up akra, this is what I get : 
![image](https://cloud.githubusercontent.com/assets/2664797/23130125/25ffefd0-f73a-11e6-9bbc-eb584e9dcce3.png) . Did you try the latest checked-in files like me? It's possible that by running stardict I messed it up.

**Comment by damooo** [comment]
don't know what is the problem, but i too got same above thing. just recompiled source again with stardict-editor version in my arch linux, and result worked well.. pushed compiled output files.

**Comment by vvasuki** [comment]
Seems all right now, thanks!

**Comment by damooo** [comment]
updated,added script which will generate final babylon with  foot linking and other. 

'make_vei_babylon.sh' creates babylon file from vei.txt file; it will take some 15 minutes to complete.
It creates 'mula_vedic_index.babylon'  file, intermediate file  from which we can create customised version of babylon file using 'vei_babylon.customiser.sh' script in same folder.
make_vei_babylon.sh creates 'vedic_index.babylon', and 'vedic_index_styled.babylon' files (which are pre customized with default options) , along with mula_vedic_index.babylon.

first run bash make_vei_babylon.sh, will create minimal version and and styled version and intermediate mula_vedic_index.babylon file from which we can create any customised version "vedic_index.babylon_customized" with options we selected from vei_babylon_customiser.sh .                                                                                       an example customized version is created in folder.
added option in customiser to transliterate IAST to devanagari in text, and styling , etc.
