### ISSUE TITLE
Remove non optitrans latin-transliterated headwords from all dictionaries.

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/stardict-sanskrit#11]
namaste dAmodara, An important request - please remove non optitrans latin-transliterated headwords from all dictionaries. For example:
nAra|naara|नार|relating to or proceeding from men in spoken sanskrit dictionary.

I suspect that if the nara or nAra exists as a synonym in even one dictionary, on the desktop goldendict program, unrelated entries from other dictionaries are also pulled up.

Context and example: I just searched for naara and नार on goldendict on my ubuntu machine, and it was hell - a very bad user experience where a lot of "nara" results were returned - http://pastebin.com/YgCVehcL . This dissuades users from looking at the dictionary 😚.

If possible prioritize over other projects..

**Comment by damooo** [comment]
oh, i tried to not let them in in all dicts, but this spokensanskrit, i am forced to kept them because , they used that type of transliteration to provide search results, and most importantly hyperlinking , and double clicking in this case. even if you see the case of   ' श '  , they used 'za' instead of 'sha' or what ever near.    And to provide compatability with them i kept them, and only for those cases added extra normal optitrans. So if we want we can remove all these cases, we have to do it in search and in description results too... because, otherwise it's hyperlinking benifit will not be there. if it is not problem for end users, i will remove all these cases. and will update...

**Comment by damooo** [comment]
And if possible tell me some info on how actually golden dict search functionality is working, i.e what relation or bonding it is considering between head words, to give results. some time it is pulling from all others , with linking of non searched synonym, which is helpful to us if these type of dicts are not there and some times not pulling. if we have perfect understanding then it will be great. And remaining dicts, no problem with these, as i didn't want to insert those.

**Comment by vvasuki** [comment]
On the desktop version of goldendict, this is what seems to be happening when you search for a word:
* All synonyms from all dictionaries are gathered.
* entries for all those synonyms from all dictionaries are shown.

On the mobile version of goldendict, this is what seems to be happening when you search for a word:
* All synonymous entries within a dictionary are shown.

dAmodara, reg spokensanskrit I think we should sacrifice this hyperlinking functionality so as to provide an overall better user experience.

**Comment by damooo** [comment]
removed them in spokensanskrit, and updated. repetitions too removed. Soon will remove their html, and write it from scratch with hyperlinks.

**Comment by vvasuki** [comment]
Phew - that's much better, thanks!
