### ISSUE TITLE
Avoid using suffix "-sa" to mean "Devanagari script" (rather than "Sanskrit language")

### ISSUE THREAD

**Issue by shreevatsa** [sanskrit-coders/stardict-sanskrit#2]
It is a bit confusing that many of the dictionary names contain "sa" in their names: it seems like it means Sanskrit language, but actually it's being used to mean "Devanagari script". I recommend using either "dev" or "deva" (as opposed to "rom" or "roma", or even better "itrans" or "iast" or whatever).

**Comment by vvasuki** [comment]
Very good point. I too noticed it and therefore switched to using "dev" -
as in purANa-index-dev and rv-padapATha-dev. But, I worry about switching
now since it will lead to old users who install these dictionaries using
update scripts to have both the older unerased version (kalpadruma-sa) and
the newer version (kalpadruma-dev). This will cause them some
inconvenience, so that I must now wonder if my aesthetic pleasure is worth
that.

2016-02-16 15:33 GMT-08:00 Shreevatsa <notifications@github.com>:

> It is a bit confusing that many of the dictionary names contain "sa" in
> their names: it seems like it means Sanskrit language, but actually it's
> being used to mean "Devanagari script". I recommend using either "dev" or
> "deva" (as opposed to "rom" or "roma", or even better "itrans" or "iast" or
> whatever).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sanskrit-coders/stardict-sanskrit/issues/2>.
>



-- 
--
Vishvas /विश्वासः

**Comment by vvasuki** [comment]
A shortwhile after this was opened, the semantics of sa- changed to : sanskrit headword! So, no longer means devanAgarI headword. This makes sense now a single dictionary can provide headwords in various representations (devanAgarI, optitrans, etc..)

**Comment by gasyoun** [comment]
> This makes sense now a single dictionary can provide headwords in various representations

Good point.
