### ISSUE TITLE
Edgerton Buddhist Hybrid Sanskrit Dictionary added

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/stardict-sanskrit#39]
Sanskrit / semi pali  -> English kind of dictionary.

sa-head/edgerton-buddhist-hybrid folder.
Short code BHS

**Comment by vvasuki** [comment]
how are these short codes used? why's that being mentioned here?

**Comment by funderburkjim** [comment]
The short codes are the way dictionaries are identified in the Cologne data. For convenience, rather than writing Buddhist Hybrid Sanskrit Dictionary, we use the shorter BHS.  Makes programming with multiple dictionaries easier.   Quite reasonable to use long forms when presenting something to users.

**Comment by vvasuki** [comment]
Ok, it later occurred to me that including them here is good for search convenience and matching with cologne sources.

**Comment by gasyoun** [comment]
> Ok, it later occurred to me that including them here is good for search convenience and matching with cologne sources.

Exactly.
