### ISSUE TITLE
Update DCS frequencies

### ISSUE THREAD

**Issue by avinashvarna** [sanskrit-coders/stardict-sanskrit#86]
The DCS frequencies available [here](https://github.com/sanskrit-coders/stardict-sanskrit/tree/master/sa-kAvya/dcs-frequency) are out of date and need to be updated. One solution could be to add a "reduce" = "_count" to the couchdb dcs_sentences view that indexes words. Then using the group=true query will automatically generate the frequencies based on the latest state of the database.

**Comment by vvasuki** [comment]
नमस्करोम्य् अविनाश, 
उपायो रुचिकरः - उपकृतोऽस्मि। 
vedavaapiक्षेत्रे dcs-कोश-पालनाधिकारस् ते दत्तः, येन यथापेक्षं शोधनं वर्धनं च साधयेः‌ कदाचित् - हाङ्गौट्-द्वारा प्रवेशविवरणानि प्रेषितानि।

**Comment by gasyoun** [comment]
> are out of date 

How did you notice it?

**Comment by avinashvarna** [comment]
@gasyoun 
I am running some experiments on using the DCS database to do NLP tasks for our sanskrit_parser project (https://github.com/kmadathil/sanskrit_parser) and Vishvas concurrently suggested using the DCS frequencies for ranking the splits found (https://github.com/kmadathil/sanskrit_parser/issues/31). Following the links, I noticed that the frequencies are out of date with what I was seeing from a local copy of the couchdb database using the reduce idea I mentioned earlier.
Will be posting my DCS experiments to github soon if you are interested.

**Comment by avinashvarna** [comment]
Looks like vishvas has fixed it in the couchdb server already. http://vedavaapi.org:5984/dcs_sentences/_design/index_words/_view/index_words?group=true returns the frequencies correctly.

**Comment by gasyoun** [comment]
> Will be posting my DCS experiments to github soon if you are interested.

Eagerly waiting. 

> DCS frequencies for ranking

We use it for https://github.com/sanskrit-lexicon/Cologne/issues/156

In your case

**Comment by funderburkjim** [comment]
I've been working with Marcis in the link he mentions above.  As part of that, we are using some word frequency listing supposedly somehow derived from the DCS (Digital Corpus Sanskrit](http://kjc-sv013.kjc.uni-heidelberg.de/dcs/index.php?contents=intro_dcs_design).  

However, I have no definite idea of the methodology behind the frequences, so no definite idea of what the frequencies mean.

In looking at the link to dcs-frequency.csv of this repository,  what is the definition of the fields?
For instance here are the first two records
```
ū,indeclinable,ind,13:6;55:1;74:6,13,
a,indeclinable,ind,14:2;13:345;31:1;55:2;68:2;74:18;89:1;96:4;103:1;117:2;189:1;8:1,380,
```

In this list, is one of the numbers a frequency? e.g., is the first number (13 for ū, 14 for a) the frequency?
And what do the other numbers represent?

Thanks for any insight you have time to provide on these questions.

**Comment by vvasuki** [comment]
namaste jim -

ū,indeclinable,ind,13:6;55:1;74:6,13


means 13 occurances in total, with 6 in text 13, 1 in text 55 and so
on. as Avinash said, this is outdated.


from mobile - excuse spelling

On Aug 9, 2017 15:47, "funderburkjim" <notifications@github.com> wrote:

I've been working with Marcis in the link he mentions above. As part of
that, we are using some word frequency listing supposedly somehow derived
from the DCS (Digital Corpus Sanskrit](http://kjc-sv013.
kjc.uni-heidelberg.de/dcs/index.php?contents=intro_dcs_design).

However, I have no definite idea of the methodology behind the frequences,
so no definite idea of what the frequencies mean.

In looking at the link to dcs-frequency.csv of this repository, what is the
definition of the fields?
For instance here are the first two records

ū,indeclinable,ind,13:6;55:1;74:6,13,
a,indeclinable,ind,14:2;13:345;31:1;55:2;68:2;74:18;89:1;96:4;103:1;117:2;189:1;8:1,380,

In this list, is one of the numbers a frequency? e.g., is the first number
(13 for ū, 14 for a) the frequency?
And what do the other numbers represent?

Thanks for any insight you have time to provide on these questions.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/sanskrit-coders/stardict-sanskrit/issues/86#issuecomment-321402324>,
or mute the thread
